### ISSUE TITLE
LDAP SSL Connection failed  on Windows 2012R2

### ISSUE THREAD

**Issue by xtavras** [MutonUfoAI/pgina#30]
Hi,

like title says, SSL connection to LDAP doesn't work with latest PGina, if I change connection to non encrypted, everything is fine. SSL port is reachable, tested both StartTLS and SSL on both ports (389 and 636). I have identical setup on Windows 2008R2  and it works there fine too.

here some info:

```
2016-03-31 12:21:46,604 [1|ERROR] LdapServer: LdapException: LDAP-Server is not available. 
2016-03-31 12:21:46,604 [1|ERROR] LdapPlugin: Server unavailable: , LDAP-Server is not available.
2016-03-31 12:21:46,604 [1|DEBUG] LdapServer: Closing LDAP connection to ldapslave.example.com.
2016-03-31 12:21:46,620 [1|WARN ] PluginDriver:961e934b-8773-4b03-8a1a-4956b2d9bda8: 0f52390b-c781-43ae-bd62-553c77fa4cf7 Failed with Message: Failed to contact LDAP server.
```

I've tested both 3.2.4.1 and old 3.1.8.0 versions.

Best,
Stan

**Comment by MutonUfoAI** [comment]
You lack proper cert support

open the eventlog
application and service logs
directory service

Log Name:      Directory Service
Source:        Microsoft-Windows-ActiveDirectory_DomainService
Date:          01.04.2016 12:15:06
Event ID:      1220
Task Category: LDAP Interface
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      contoso-DC1.contoso.local
Description:
LDAP over Secure Sockets Layer (SSL) will be unavailable at this time because the server was unable to obtain a certificate. 


If so follow ...
http://gregtechnobabble.blogspot.co.at/2012/11/enabling-ldap-ssl-in-windows-2012-part-1.html

**Comment by xtavras** [comment]
Hi @MutonUfoAI ,

sorry for late response, didn't get notification.
I don't have such logs in eventlog, probable because I don't have AD DS on the server. 

Best,
Stan

**Comment by MutonUfoAI** [comment]
I've tested this with my test AD 2008R2 and it worked as soon as I've added proper cert support.
If your environment is different i suggest you use wireshark first to see what exactly happens and go on from there.

**Comment by MutonUfoAI** [comment]
no respond .....
