### ISSUE TITLE
Ldap Plugin strange behavior

### ISSUE THREAD

**Issue by shizacat** [MutonUfoAI/pgina#31]
Hello
I was testing Ldap plugin and he strange to work:
Accout: user1 - p1
- login( user1, p1) - Sussess
- logout

- changePassword(u1, p2)
- login( user1, p1) - **Sussess !!! Why**
- logout
- login( user1, p2) - Sussess
- logout
- login( user1, p1) - **Fail**

**Comment by MutonUfoAI** [comment]
There is a log file
pGina.InstallUtil_log.txt

pgina version and configuration?

**Comment by shizacat** [comment]
Version: 3.9.9.1
[pGina.InstallUtil_log.txt](https://github.com/MutonUfoAI/pgina/files/230031/pGina.InstallUtil_log.txt)

**Comment by MutonUfoAI** [comment]
sorry got it wrong i need
pGina.Service.ServiceHost_log.txt

**Comment by shizacat** [comment]
username: mav

[pGina.Service.ServiceHost_log.txt](https://github.com/MutonUfoAI/pgina/files/231214/pGina.Service.ServiceHost_log.txt)

**Comment by MutonUfoAI** [comment]
first i realize ansi log files aren't any good here https://github.com/MutonUfoAI/pgina/commit/fc04206b63782a938ab57cbb1bf4cd7ed6437dfb

.)login( user1, p1) - Sussess
Than i see you've logged in first with wrong credentials " mav" istead of "mav" but than the logon succeeded.
.)logout
.)changePassword(u1, p2)
.)login( user1, p1) - Sussess !!! Why
than you've logged off and 30 sec later you re-logged into the system using "mav"
but the ldap plugin returned "Authentication via LDAP failed. Invalid credentials"
Thats correct, you've changed the pwd!
Than the localmachine plugin come into play and succeeded in authenticate user "mav" because the user "mav" exists on the local machine and the pwd do match.
In the gateway phase of the local machine plugin the new pwd for user "mav" is applied on the local machine.
FIX:
  .)dont use the local machine to authenticate local users
  .)or enable in ldap settings/authorization "deny when ldap authentication fails"
  .)or use internal pgina change pwd abilities to change pwd's
.)logout
.)login( user1, p2) - Sussess
You than logout and relogged in again.
Ldap authentication suceeded but localmachine authentication failed which results in a success (use authorization, one fail will than result in authorization failed)
.)logout
.)login( user1, p1) - Fail
Again log-off followed by a re-login but both ldap and local machine failed.
because the pwd on the ldap is different and the local pwd too

Everything as it should be!
You should really read the doc (there is a help button!)
http://mutonufoai.github.io/pgina/documentation.html
I know its outdated ...

**Comment by shizacat** [comment]
Thank you! 
That work!
I set checkbox - "deny when ldap authentication fails" - and works as it should be

But again problem - If cable disconnect - that not login - "Deny because LDAP Authentication failed, or did not execute" - may be i not see one more setting
Can implement this behavior - so that when the LDAP server is accessible only to the user to check only on the server. And when not available from the cache (Local plugin)
CheckBox - "Allow when server is unreachable" - work after checkbox "Deny when LDAP authentication fails"

**Comment by MutonUfoAI** [comment]
You need to authenticate a user first then by default this stage returns false,
but you only have ldap plugin activated in this stage.
It will return false and therefore the login will fail on the authentication stage.

"Allow when server is unreachable" is meant for authorization only.
If the Ldap plugin is unable to authenticate a user but the local machine succeeded to authenticate,
than the ldap plugin will set authorization (if activated) to false.
In that case the "Allow when server is unreachable" will prevent a false return
Authorization returns success by default, as soon as one plugin returns false the authorization stage returns false.

If you want a fallback you need to enable authentication on the local machine plugin too.
Disable authorization because it returns true by default,
and encourage your users to use pgina (ctrl+alt+del) to set there pwd's instead of doing this by hand on your ldap.

What you want is illogical, like a windows domain without a network.
(a domain member without a network will only authenticate users he knows off with there last working pwd)

btw.
Local users on this machine that do not contain a comment of "pGina created" ar'nt processed by pgina in the same way.
Meaning users are checked only for there username, pwd, expired pwd, is user active .... as a normal login would be, but no plugin will be called.
