### ISSUE TITLE
Make sure loggen in user has admin rights from AD

### ISSUE THREAD

**Issue by abdlquadri** [MutonUfoAI/pgina#38]
Dear PGina Devs,

We really appreciate your great effort on this project.

We have implemented a service based on PGINA fork. We have a challenge where the logged in user is not recognized as an Admin.

My question is how do we configure the LDAP plugin to allow PGINA give admin roles from AD to logged in  user.

This is needed so that admin actions like installation can be done while logged in to the PC via PGINA.

Thank You.

**Comment by MutonUfoAI** [comment]
If this PC is member of the domain and
your user is authenticated by this domain then
pgina wont call any plugin.

**Comment by MutonUfoAI** [comment]
Is this workstation member of an AD?
Is the user who wants to login member of this AD?
If both questions are answered with yes
https://github.com/MutonUfoAI/pgina/blob/master/pGina/src/Service/Impl/Service.cs#L317
than pgina will validate the credentials by query the AD and return true or false based on that result to winlogon.
In that case you'll find a log entry stating "domain logon: Username: ......"
instead of "Processing LoginRequest for: ....." in the pgina log pGina.Service.ServiceHost_log.txt

By using an AD there is no need to solve your problem by using pgina.
https://www.google.at/search?q=give+domain+user+local+admin+rights+computer+group&cad=h

**Comment by abdlquadri** [comment]
Ok Hans,

I really appreciate you patience with me.

I will check these more closely and report back.
