### ISSUE TITLE
Login simulator

### ISSUE THREAD

**Issue by db4** [MutonUfoAI/pgina#62]
Why it has been removed? I can't find any explanation except "do not use it" in #18 and #20. Then how to check that e.q. LDAP authentication succeeds before getting problems during login stage?

**Comment by MutonUfoAI** [comment]
Because results are not reliable.
Plugin don't "know" that this is just a simulation.
Stuff that got triggered by the simulator is not removed.
.....

There is no need for a simulator, because you cant lock yourself out.
The fork does things in a different way, it wont touch your local users.
http://mutonufoai.github.io/pgina/documentation.html
