### ISSUE TITLE
W10 login using Microsoft login

### ISSUE THREAD

**Issue by selvasof** [MutonUfoAI/pgina#63]
Using pgina as a framework with a custom secure authentication that on successful authentication then provides the username and password. Local login works, but can't figure out how to login if account is configured for Microsoft login. Can anyone tell me how to do this.  Thanks.

**Comment by MutonUfoAI** [comment]
It's not supported!

**Comment by selvasof** [comment]
Thanks. 

Do you have an idea of how the Microsoft login works, If I could figure that out, it might be possible for me to add code for pgina to do this as an alternative option,  W10 users set to Microsoft login can login even if no internet (Microsoft login logs in and if internet, sets up various resources at Microsoft),. Since Microsoft makes setting up local login accounts not obvious, it's my guess many people are configured this way and may even be using various Microsoft based resources and apps.

Appreciate you fast response.

**Comment by MutonUfoAI** [comment]
I have no idea how they do it.

**Comment by selvasof** [comment]
ok thanks

**Comment by sethwalsh** [comment]
You will need to research about CredentialProvider v2 along with Microsoft Passport and Windows Hello in order to make that work.

https://msdn.microsoft.com/en-us/library/windows/desktop/mt158211(v=vs.85).aspx#custom_credential_providers

and

https://docs.microsoft.com/en-us/windows/access-protection/hello-for-business/hello-identity-verification
